import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/context/ThemeProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body className="w-full">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="m-auto w-full min-w-[240px] max-w-[760px] p-[10px] sm:p-[20px]">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
